language: php

php:
  - 7.1
  - 7.0

sudo: required

services:
  - docker

before_script:
  - pip install --user codecov
  - composer self-update && composer install
  - sudo kill -9 `sudo lsof -t -i:80`
  - docker build -t my_app .
  - docker run -d -p 80:80 my_app

script:
  - ./vendor/bin/phpunit

after_success:
  - codecov
