test:
    method: [GET, POST]
    path: /
    handler: MatthiasMullie\ApiExample\ExampleController

another_test:
    method: GET
    path: /hello/{name}
    handler: MatthiasMullie\ApiExample\ExampleController
